spring:
  mail:
    password: ${MAIL_PASSWORD}

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

api:
  key: ${API_KEY}

app:
  root:
    frontend: https://linkplaza.netlify.app
