spring:
  application:
    name: LinkPlaza API
  config:
    import: secret.yml
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/linkplaza?serverTimezone=UTC
    username: root
    password: ""
  mail:
    host: smtp.gmail.com
    port: 587
    username: huaripataricardo3@gmail.com
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
    default-encoding: UTF-8

server:
  port: 8080

app:
  root:
    frontend: http://localhost:4200
